### ISSUE TITLE
More of a feature request... more decimals/configurable for values

### ISSUE THREAD

**Issue by cconstab** [JErazo7/gauge#1]
Allow the decimal point to be configurable.

pretty_gauge.dart line 279
 
                    Text('${_currentValue.toStringAsFixed(1)}',

I changed my cache value to 2 and it looks very pretty for my use case! But being configurable would allow me not to have any decimals for example on the RPM meter.

If you would prefer a PR happy to do that too.. Nice work and thanks

@cconstab 

For example

![image](https://user-images.githubusercontent.com/6131216/150009314-493c97ee-739b-4757-a9ba-c662111ab8e9.png)

**Comment by JErazo7** [comment]
@cconstab please, if you could do a PR is Welcome. Thanks you

**Comment by cconstab** [comment]
Cool beans will do
